### ISSUE TITLE
[Crash] Failed to serialize 'mods'.

### ISSUE THREAD

**Issue by luoxingzlx** [Yesterday17/Probe#1]
启动崩溃
probe 0.1.18
forge 14.23.5.2815
https://paste.ubuntu.com/p/hrwCy3GsQN/

**Comment by Yesterday17** [comment]
我之后发布一个配置文件控制模块开关的版本吧
这crash report唯一有用的东西就是modlist了（泣）

**Comment by Yesterday17** [comment]
https://github.com/Yesterday17/Probe/blob/1e643f018045d05d162ed88dc0d8a1fa0e2c19ed/src/main/java/cn/yesterday17/probe/serializer/ModSerializer.java#L28-L29
目前推断是这里出现了循环嵌套导致stackoverflow

**Comment by Yesterday17** [comment]
@luoxingzlx 我推了 [v0.1.19](https://minecraft.curseforge.com/projects/probe/files/2682564) 版本，你你可以试着再跑一遍然后把 crashreport 发过来
也可以尝试在配置文件里禁用一些模块，比如我推测的 `enableMods`。
目前看来绝对不会出问题的应该是`enableOreDictionary`，这个不用试。

**Comment by luoxingzlx** [comment]
@Yesterday17 enableMods关掉后启动成功，这是没关时的crash，https://paste.ubuntu.com/p/HFcWCNTZ8m/

**Comment by Yesterday17** [comment]
@luoxingzlx 试试这个版本，Github没法传jar，我就打了个包。

[probe-0.1.20.zip](https://github.com/Yesterday17/Probe/files/2923196/probe-0.1.20.zip)

**Comment by luoxingzlx** [comment]
@Yesterday17 运行正常
