### ISSUE TITLE
Why is SetPrettyWriting() commented out in the GsonBuilder in Probe.java ?

### ISSUE THREAD

**Issue by cschierig** [Yesterday17/Probe#3]
It's much easier to navigate through the file when SetPrettyWriting() is enabled. Even though you mostly don't need it, reading the file helps me when I am looking for certain things. Is there any reason for it being disabled (l. 59, Probe.java)?

**Comment by Yesterday17** [comment]
As it's generated for [ZenScript][zenscript-link], I thought the smaller the filesize is, the faster it could be when loading.
I can make a boolean for it in config.

[zenscript-link]: https://github.com/Yesterday17/ZenScript

**Comment by Yesterday17** [comment]
I've made a new release for it. You can see it soon.
https://minecraft.curseforge.com/projects/probe/files/2711493

**Comment by Yesterday17** [comment]
I'm closing it as it's solved.
