### ISSUE TITLE
Probe crashes the modpack

### ISSUE THREAD

**Issue by rlnt** [Yesterday17/Probe#6]
I like the VSCode extension from you and wanted to also install the probe mod for my new modpack to get intellisense but it currently crashes the modpack.

Minecraft: 1.12.2
Forge: 14.23.5.2847
Probe: v0.1.16
Crash report: https://pastebin.com/42kp3AvM

**Comment by Yesterday17** [comment]
#1 fixed a similar bug(sorry for not using English at that issue), could you please try to use the latest version of Probe?

If it still crashes, you can try to disable some utilities in the configuration file(a feature introduced in v0.1.19). It provides more precise information for debugging.

**Comment by rlnt** [comment]
I mean I would use a newer version if there was one but I only found v0.1.16 on the releases and couldn't find the mod on curseforge.

**Comment by rlnt** [comment]
Nevermind I found the Curseforge page. You should really leave a link to that on the github readme. I was confused since you have no releases here and I wasn't able to find the Probe mod on curseforge because its only release is an alpha and alphas are not listed.

**Comment by rlnt** [comment]
Works with the newest version.
Sorry for replying so late but I wasn't able to test it earlier.
