### ISSUE TITLE
Items and blocks hidden from JEI show up as "not existing"

### ISSUE THREAD

**Issue by copygirl** [Yesterday17/Probe#8]
When the mod is run after the scripts have been applied, it looks like items and blocks hidden from JEI, either using `JEI.hide` or `JEI.removeAndHide`, show up as missing using the extension.

![image](https://user-images.githubusercontent.com/272586/82838250-e540cb80-9ecb-11ea-9204-7b4a18cf1b83.png)

I get the following error:
`BracketHandler <minecraft:gold_ore> does not exist.`

**Comment by Yesterday17** [comment]
Probe v0.1.24 has released. Waiting for CurseForge...

https://www.curseforge.com/minecraft/mc-mods/probe/files/2984104
